### ISSUE TITLE
java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'

### ISSUE THREAD

**Issue by 1024ping** [binance/binance-connector-java#47] opened 2022-08-10 07:10 UTC
java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
	at com.binance.connector.client.utils.RequestBuilder.buildApiKeyRequest(RequestBuilder.java:56)
	at com.binance.connector.client.utils.RequestHandler.sendApiRequest(RequestHandler.java:48)
	at com.binance.connector.client.utils.RequestHandler.sendSignedRequest(RequestHandler.java:77)
	at com.binance.connector.client.impl.spot.Wallet.fundingWallet(Wallet.java:448)

**Comment by chairz** [comment] 2022-08-11 02:24
Please install the correct version of OKHTTP3 listed in `pom.xml`

**Comment by LastPirate** [comment] 2022-12-13 20:56
@chairz Hello. I've faced totally the same issue, searched any solution but didn't find any working solution. As you said I've injected OkHttp3 dependency with version from project's pom.xml and it doesn't working. Here is my dependencies:

`
  implementation("io.github.binance:binance-connector-java:1.11.0")
  api("com.squareup.okhttp3:okhttp") {
    version { strictly("4.9.2") }
  }
`

So I've tried to dive deeply and found that errors caused by `com.binance.connector.client.utils.RequestBuilder` when in tries to call `RequestBody.create("", JSON_TYPE)` during make **PUT or POST** request. After dependency tree inspection I can say that for some reason version of `okhttp3:okhttp` is `3.14.9` wiring automatically and when I'm opening it's `RequestBody` class-file I see the next method signatures:

`
  public static RequestBody create(@Nullable MediaType contentType, String content) {}
  public static RequestBody create(final @Nullable MediaType contentType, final ByteString content) {}
  public static RequestBody create(final @Nullable MediaType contentType, final byte[] content) {}
  public static RequestBody create(final @Nullable MediaType contentType, final byte[] content, final int offset, final int byteCount) {}
  public static RequestBody create(final @Nullable MediaType contentType, final File file) {}
`

When I am pointing version  of `okhttp3:okhttp` strictly to `4.9.2` from your `pom.xml` and manually opening  `com.binance.connector.client.utils.RequestBuilder` again I can see that error still appears because of there is with compatible signature:

`
public abstract class RequestBody public constructor() {
    public companion object {
        @kotlin.jvm.JvmStatic @kotlin.Deprecated public final fun create(contentType: okhttp3.MediaType?, file: java.io.File): okhttp3.RequestBody { /* compiled code */ }

        @kotlin.jvm.JvmStatic @kotlin.Deprecated @kotlin.jvm.JvmOverloads public final fun create(contentType: okhttp3.MediaType?, content: kotlin.ByteArray, offset: kotlin.Int /* = compiled code */, byteCount: kotlin.Int /* = compiled code */): okhttp3.RequestBody { /* compiled code */ }

        @kotlin.jvm.JvmStatic @kotlin.Deprecated public final fun create(contentType: okhttp3.MediaType?, content: kotlin.String): okhttp3.RequestBody { /* compiled code */ }

        @kotlin.jvm.JvmStatic @kotlin.Deprecated public final fun create(contentType: okhttp3.MediaType?, content: okio.ByteString): okhttp3.RequestBody { /* compiled code */ }

        @kotlin.jvm.JvmStatic @kotlin.jvm.JvmName public final fun java.io.File.asRequestBody(contentType: okhttp3.MediaType? /* = compiled code */): okhttp3.RequestBody { /* compiled code */ }

        @kotlin.jvm.JvmStatic @kotlin.jvm.JvmOverloads @kotlin.jvm.JvmName public final fun kotlin.ByteArray.toRequestBody(contentType: okhttp3.MediaType? /* = compiled code */, offset: kotlin.Int /* = compiled code */, byteCount: kotlin.Int /* = compiled code */): okhttp3.RequestBody { /* compiled code */ }

        @kotlin.jvm.JvmStatic @kotlin.jvm.JvmName public final fun kotlin.String.toRequestBody(contentType: okhttp3.MediaType? /* = compiled code */): okhttp3.RequestBody { /* compiled code */ }

        @kotlin.jvm.JvmStatic @kotlin.jvm.JvmName public final fun okio.ByteString.toRequestBody(contentType: okhttp3.MediaType? /* = compiled code */): okhttp3.RequestBody { /* compiled code */ }
    }

    public open fun contentLength(): kotlin.Long { /* compiled code */ }

    public abstract fun contentType(): okhttp3.MediaType?

    public open fun isDuplex(): kotlin.Boolean { /* compiled code */ }

    public open fun isOneShot(): kotlin.Boolean { /* compiled code */ }

    public abstract fun writeTo(sink: okio.BufferedSink): kotlin.Unit
}
`

**Comment by LastPirate** [comment] 2022-12-13 20:58
@chairz how to fix this?

**Comment by aisling-2** [comment] 2023-02-16 08:53
Closing this topic due to lack of updates, if there's questions in the future, feel free to reopen.

**Closed by aisling-2** 2023-02-16 08:53 UTC
Labels: Review
